name: Guestbook

on:
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  update_guestbook:
    name: Update guestbook
    # 이슈 제목이 'Guestbook' 일 때만 동작
    if: ${{ github.event.issue.title == 'Guestbook' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update guestbook from comments (chat bubbles)
        uses: actions/github-script@v6
        with:
          script: |
            // 1) 댓글 가져오기 (최대 100 + 페이지네이션)
            const query = `
              query($owner:String!, $name:String!, $issue_number:Int!, $after:String) {
                repository(owner:$owner, name:$name){
                  issue(number:$issue_number) {
                    comments(first:100, orderBy:{direction:DESC, field:UPDATED_AT}, after:$after) {
                      nodes {
                        author { avatarUrl(size: 40) login url }
                        url
                        body
                        updatedAt
                      }
                      pageInfo { hasNextPage endCursor }
                    }
                  }
                }
              }`;
            const vars = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number,
              after: null
            };

            let nodes = [];
            while (true) {
              const res = await github.graphql(query, vars);
              const page = res.repository.issue.comments;
              nodes = nodes.concat(page.nodes);
              if (!page.pageInfo.hasNextPage) break;
              vars.after = page.pageInfo.endCursor;
            }

            // 2) 유틸: escape + 줄바꿈
            const esc = (s='') =>
              s.replace(/&/g,'&amp;')
               .replace(/</g,'&lt;').replace(/>/g,'&gt;')
               .replace(/"/g,'&quot;').replace(/'/g,'&#39;');
            const withBr = (s='') => esc(s).replace(/\r?\n/g,'<br />');

            // 3) 시간 포맷 (UTC). 한국 시간 원하면 'Asia/Seoul' 로 변경
            const fmt = iso => new Date(iso).toLocaleString('en-US', { timeZone:'Asia/Seoul', hour12:false });

            // 4) 채팅 버블(최근 20개) + 스크롤 컨테이너
            const MAX = 20;
            const recent = nodes.slice(0, MAX);

            const bubbles = recent.map(c => [
              '<div style="display:flex; gap:10px; margin:10px 0;">',
              `  <a href="${c.author.url}" target="_blank" style="text-decoration:none;">`,
              `    <img src="${c.author.avatarUrl}" alt="${esc(c.author.login)}" width="40" height="40" style="border-radius:50%;"/>`,
              '  </a>',
              '  <div style="flex:1;">',
              '    <div style="display:flex; align-items:baseline; gap:8px; flex-wrap:wrap;">',
              `      <a href="${c.author.url}" target="_blank" style="font-weight:600; text-decoration:none;">${esc(c.author.login)}</a>`,
              `      <a href="${c.url}" target="_blank" style="color:#64748b; font-size:12px; text-decoration:none;">${fmt(c.updatedAt)}</a>`,
              '    </div>',
              `    <div style="background:#f6f8fa; border:1px solid #e5e7eb; border-radius:10px; padding:10px; margin-top:6px; line-height:1.5;">${withBr(c.body)}</div>`,
              '  </div>',
              '</div>'
            ].join('\n')).join('\n');

            const container = [
              '<div style="max-height:360px; overflow-y:auto; padding:6px 8px; border:1px solid #e5e7eb; border-radius:12px; background:#fff;">',
              bubbles || '<div style="color:#64748b;">No entries yet — be the first!</div>',
              '</div>'
            ].join('\n');

            // 5) README 마커 사이 교체
            const fs = require('fs');
            const path = 'README.md';
            const start = '<!-- Guestbook -->';
            const end   = '<!-- /Guestbook -->';
            const readme = fs.readFileSync(path, 'utf8');

            const re = new RegExp(`(?<=${start}[\\s\\S]*?\\n)[\\s\\S]*?(?=${end}|$(?![\\n]))`, 'm');
            const next = readme.match(re)
              ? readme.replace(re, container)
              : readme.replace(start, `${start}\n${container}\n`);

            if (next !== readme) {
              fs.writeFileSync(path, next, 'utf8');
            }

      - name: Commit & push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git add README.md
            git commit -m ':sparkles: update guestbook (chat)'
            git push
          else
            echo "No changes to commit."
          fi
